addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.7")
addSbtPlugin("com.github.sbt"            % "sbt-release"         % "1.1.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.33")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
