addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.3.19")
addSbtPlugin("com.github.gseitz"         % "sbt-release"         % "1.0.13")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.2.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.11")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.10")
