addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.8.0")
addSbtPlugin("com.github.gseitz"         % "sbt-release"         % "1.0.13")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.23")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.15")
